from cv2 import FONT_HERSHEY_SIMPLEX
from enums.ColormapEnum import Colormap

### GUI CONSTANTS
WINDOW_TITLE: str = "Thermal Camera"
DEFAULT_FULLSCREEN: bool = False
DEFAULT_HUD_VISIBLE: bool = True
DEFAULT_LAST_SNAPSHOT_TIME: str = ""
DEFAULT_RECORDING_START_TIME: float = 0
DEFAULT_RECORDING_DURATION: str = "00:00:00"
DEFAULT_FONT: int = FONT_HERSHEY_SIMPLEX
DEFAULT_TEMPERATURE_UNIT_SYMBOL: str = "C"

# Scale
DEFAULT_SCALE: int = 3
SCALE_MAX: int = 5
SCALE_MIN: int = 1
SCALE_INCREMENT: int = 1

# Delays
KEY_PRESS_DELAY: int = 1

### IMAGE PROCESSING CONSTANTS
DEFAULT_COLORMAP: Colormap = Colormap.NONE

# Contrast
DEFAULT_CONTRAST: float = 1.0
CONTRAST_MAX: float = 3.0
CONTRAST_MIN: float = 0.0
CONTRAST_INCREMENT: float = 0.1

# Blur
DEFAULT_BLUR_RADIUS: int = 0
BLUR_RADIUS_MAX: int = 3
BLUR_RADIUS_MIN: int = 0
BLUR_RADIUS_INCREMENT: int = 1

# Threshold
DEFAULT_THRESHOLD: int = 2
THRESHOLD_MAX: int = 3
THRESHOLD_MIN: int = 0
THRESHOLD_INCREMENT: int = 1